spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eager_ultras
    username: postgres
    password: 123

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  sql:
    init:
      mode: never

server:
  error:
    include-message: always

app:
  upload-dir: ${user.home}/eagerultras-uploads
